import argparse
import csv
import json
import os
import shutil
from pathlib import Path

import numpy as np
import pandas as pd


def _find_counterfactual_root() -> Path:
    env = os.environ.get("COUNTERFACTUAL_ROOT")
    if env:
        return Path(env)
    start = Path(__file__).resolve().parent
    for ancestor in [start] + list(start.parents):
        if (ancestor / ".git").is_dir() and (ancestor / "robust_wam").is_dir():
            return ancestor
    raise RuntimeError("Cannot find counterfactual project root. Set COUNTERFACTUAL_ROOT.")


_CF_ROOT = _find_counterfactual_root()
_EXP_ROOT = _CF_ROOT.parent

_SRC = os.environ.get("ROBOCASA_DATASET_PATH")
DEFAULT_SOURCE_ROOT = Path(_SRC) if _SRC else (_EXP_ROOT / "robocasa" / "datasets" / "v1.0" / "pretrain" / "atomic")
_OUT = os.environ.get("ROBOCASA_OUTPUT_DATASET_PATH")
DEFAULT_OUTPUT_ROOT = Path(_OUT) if _OUT else (_EXP_ROOT / "robocasa" / "datasets" / "training_no_base" / "atomic")
_FLAGS = os.environ.get("ROBOCASA_FLAGS_CSV")
DEFAULT_FLAGS_CSV = Path(_FLAGS) if _FLAGS else (_EXP_ROOT / "robocasa_base_motion_episode_flags.csv")


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Build a RoboCasa LeRobot v2.1 subset that keeps only episodes with no base "
            "motion, rewrites episode indices, and regenerates v2.1 metadata."
        )
    )
    parser.add_argument(
        "--source-root",
        type=Path,
        default=DEFAULT_SOURCE_ROOT,
        help="Source RoboCasa atomic dataset root.",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=DEFAULT_OUTPUT_ROOT,
        help="Destination root for the filtered LeRobot v2.1 subset.",
    )
    parser.add_argument(
        "--flags-csv",
        type=Path,
        default=DEFAULT_FLAGS_CSV,
        help="CSV generated by analyze_robocasa_base_motion.py.",
    )
    parser.add_argument(
        "--tasks",
        type=str,
        nargs="*",
        default=None,
        help="Optional task names. If omitted, all tasks in the CSV are processed.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Delete an existing destination collection before regenerating it.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Only print what would be generated; do not write files.",
    )
    parser.add_argument(
        "--validate",
        type=str,
        choices=["none", "after", "only"],
        default="after",
        help="Validation mode: none, after generation, or only validate existing outputs.",
    )
    return parser.parse_args()


def load_motion_flags(flags_csv: Path, tasks=None):
    tasks = set(tasks or [])
    grouped = {}
    seen_keys = set()

    with flags_csv.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        required = {"task_name", "collection_id", "dataset_id", "episode_index", "is_moving"}
        missing = required.difference(reader.fieldnames or [])
        if missing:
            raise ValueError(f"{flags_csv} missing columns: {sorted(missing)}")

        for row in reader:
            task_name = row["task_name"]
            if tasks and task_name not in tasks:
                continue

            collection_id = row["collection_id"]
            dataset_id = row["dataset_id"]
            source_episode_index = int(row["episode_index"])
            is_moving = parse_bool(row["is_moving"])
            key = (task_name, collection_id, dataset_id, source_episode_index)
            if key in seen_keys:
                raise ValueError(f"Duplicate CSV row for {key}")
            seen_keys.add(key)

            grouped.setdefault((task_name, collection_id, dataset_id), []).append(
                {
                    "source_episode_index": source_episode_index,
                    "is_moving": is_moving,
                }
            )

    for key, rows in grouped.items():
        rows.sort(key=lambda x: x["source_episode_index"])

    return grouped


def parse_bool(value: str) -> bool:
    normalized = value.strip().lower()
    if normalized in {"true", "1", "yes"}:
        return True
    if normalized in {"false", "0", "no"}:
        return False
    raise ValueError(f"Cannot parse bool from {value!r}")


def read_json(path: Path):
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def write_json(path: Path, data):
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=True, indent=4)
        f.write("\n")


def read_jsonl(path: Path):
    rows = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows


def write_jsonl(path: Path, rows):
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=True))
            f.write("\n")


def safe_remove_tree(path: Path):
    if path.exists():
        shutil.rmtree(path)


def maybe_copy_file(src: Path, dst: Path, dry_run: bool):
    if dry_run:
        return
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


def maybe_write_json(path: Path, data, dry_run: bool):
    if dry_run:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    write_json(path, data)


def maybe_write_jsonl(path: Path, rows, dry_run: bool):
    if dry_run:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    write_jsonl(path, rows)


def maybe_write_csv(path: Path, rows, fieldnames, dry_run: bool):
    if dry_run:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def source_lerobot_root(source_root: Path, task_name: str, collection_id: str):
    return source_root / task_name / collection_id / "lerobot"


def target_task_root(output_root: Path, task_name: str):
    return output_root / task_name


def validate_source_collection(lerobot_root: Path):
    meta_dir = lerobot_root / "meta"
    data_dir = lerobot_root / "data"
    videos_dir = lerobot_root / "videos"
    required = [
        meta_dir / "info.json",
        meta_dir / "episodes.jsonl",
        meta_dir / "episodes_stats.jsonl",
        meta_dir / "tasks.jsonl",
        meta_dir / "stats.json",
        meta_dir / "modality.json",
        meta_dir / "embodiment.json",
        data_dir,
        videos_dir,
    ]
    missing = [str(path) for path in required if not path.exists()]
    if missing:
        raise FileNotFoundError(f"Missing required source files under {lerobot_root}: {missing}")


def collect_video_keys(info):
    return sorted(
        key
        for key, value in info["features"].items()
        if isinstance(value, dict) and value.get("dtype") == "video"
    )


def extract_vector_series(series: pd.Series):
    if len(series) == 0:
        return np.empty((0, 0), dtype=np.float64)
    first = series.iloc[0]
    if np.isscalar(first) or isinstance(first, (bool, np.bool_)):
        arr = series.to_numpy()
        return np.asarray(arr, dtype=np.float64).reshape(-1, 1)
    stacked = np.vstack(series.to_numpy())
    return np.asarray(stacked, dtype=np.float64)


def compute_feature_stats(df: pd.DataFrame):
    stats = {}
    for column in df.columns:
        if column.startswith("observation.images."):
            continue

        values = extract_vector_series(df[column])
        if values.shape[0] == 0:
            continue

        stats[column] = {
            "mean": np.mean(values, axis=0).tolist(),
            "std": np.std(values, axis=0).tolist(),
            "min": np.min(values, axis=0).tolist(),
            "max": np.max(values, axis=0).tolist(),
            "count": [int(values.shape[0])],
            "q01": np.quantile(values, 0.01, axis=0).tolist(),
            "q99": np.quantile(values, 0.99, axis=0).tolist(),
        }
    return stats


def aggregate_episode_stats(episode_stats_rows, kept_source_episode_indices, mapping):
    per_episode = {int(row["episode_index"]): row["stats"] for row in episode_stats_rows}
    aggregated = {}
    scalar_columns = {
        "annotation.human.task_description",
        "annotation.human.task_name",
        "next.reward",
        "next.done",
        "timestamp",
        "frame_index",
        "episode_index",
        "index",
        "task_index",
        "action",
        "observation.state",
    }

    for source_episode_index in kept_source_episode_indices:
        stats = per_episode.get(source_episode_index)
        if stats is None:
            raise KeyError(f"episodes_stats.jsonl missing episode {source_episode_index}")
        for key, value in stats.items():
            if key.startswith("observation.images.") or key in scalar_columns:
                aggregated.setdefault(key, []).append(value)

    out = {}
    for key, rows in aggregated.items():
        counts = np.asarray([float(row["count"][0]) for row in rows], dtype=np.float64)
        total_count = counts.sum()
        if total_count <= 0:
            continue

        mean_stack = np.asarray([row["mean"] for row in rows], dtype=np.float64)
        std_stack = np.asarray([row["std"] for row in rows], dtype=np.float64)
        min_stack = np.asarray([row["min"] for row in rows], dtype=np.float64)
        max_stack = np.asarray([row["max"] for row in rows], dtype=np.float64)
        has_q01 = all("q01" in row for row in rows)
        has_q99 = all("q99" in row for row in rows)
        q01_stack = (
            np.asarray([row["q01"] for row in rows], dtype=np.float64) if has_q01 else None
        )
        q99_stack = (
            np.asarray([row["q99"] for row in rows], dtype=np.float64) if has_q99 else None
        )

        count_shape = (len(rows),) + (1,) * (mean_stack.ndim - 1)
        count_weights = counts.reshape(count_shape)
        weighted_mean = np.sum(mean_stack * count_weights, axis=0) / total_count
        second_moment = np.sum(
            (np.square(std_stack) + np.square(mean_stack)) * count_weights,
            axis=0,
        ) / total_count
        weighted_var = np.maximum(second_moment - np.square(weighted_mean), 0.0)
        weighted_std = np.sqrt(weighted_var)

        aggregated_entry = {
            "mean": weighted_mean.tolist(),
            "std": weighted_std.tolist(),
            "min": np.min(min_stack, axis=0).tolist(),
            "max": np.max(max_stack, axis=0).tolist(),
            "count": [int(total_count)],
        }
        if q01_stack is not None:
            aggregated_entry["q01"] = np.min(q01_stack, axis=0).tolist()
        if q99_stack is not None:
            aggregated_entry["q99"] = np.max(q99_stack, axis=0).tolist()
        out[key] = aggregated_entry

    out["episode_index"] = recompute_index_like_stats(
        values=np.asarray([mapping[src] for src in kept_source_episode_indices], dtype=np.float64),
        lengths=np.asarray(
            [float(per_episode[src]["episode_index"]["count"][0]) for src in kept_source_episode_indices],
            dtype=np.float64,
        ),
    )
    out["frame_index"] = recompute_frame_index_stats(
        lengths=np.asarray(
            [float(per_episode[src]["frame_index"]["count"][0]) for src in kept_source_episode_indices],
            dtype=np.int64,
        )
    )
    out["index"] = recompute_global_index_stats(
        lengths=np.asarray(
            [float(per_episode[src]["index"]["count"][0]) for src in kept_source_episode_indices],
            dtype=np.int64,
        )
    )
    return out


def recompute_index_like_stats(values: np.ndarray, lengths: np.ndarray):
    expanded = np.repeat(values, lengths.astype(np.int64))
    return summarize_numeric_vector(expanded)


def recompute_frame_index_stats(lengths: np.ndarray):
    pieces = [np.arange(int(length), dtype=np.float64) for length in lengths]
    expanded = np.concatenate(pieces, axis=0) if pieces else np.empty((0,), dtype=np.float64)
    return summarize_numeric_vector(expanded)


def recompute_global_index_stats(lengths: np.ndarray):
    total = int(lengths.sum())
    expanded = np.arange(total, dtype=np.float64)
    return summarize_numeric_vector(expanded)


def summarize_numeric_vector(values: np.ndarray):
    if values.size == 0:
        return {
            "mean": [0.0],
            "std": [0.0],
            "min": [0.0],
            "max": [0.0],
            "count": [0],
            "q01": [0.0],
            "q99": [0.0],
        }
    return {
        "mean": [float(np.mean(values))],
        "std": [float(np.std(values))],
        "min": [float(np.min(values))],
        "max": [float(np.max(values))],
        "count": [int(values.size)],
        "q01": [float(np.quantile(values, 0.01))],
        "q99": [float(np.quantile(values, 0.99))],
    }


def copy_episode_parquet(
    src_path: Path,
    dst_path: Path,
    target_episode_index: int,
    global_index_start: int,
    dry_run: bool,
):
    df = pd.read_parquet(src_path)
    df["episode_index"] = target_episode_index
    df["frame_index"] = np.arange(len(df), dtype=np.int64)
    df["index"] = np.arange(global_index_start, global_index_start + len(df), dtype=np.int64)

    if dry_run:
        return df

    dst_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_parquet(dst_path, index=False)
    return df


def copy_episode_videos(
    src_videos_root: Path,
    dst_videos_root: Path,
    video_keys,
    source_episode_index: int,
    target_episode_index: int,
    chunks_size: int,
    dry_run: bool,
):
    source_name = f"episode_{source_episode_index:06d}.mp4"
    target_name = f"episode_{target_episode_index:06d}.mp4"
    source_chunk = source_episode_index // chunks_size
    target_chunk = target_episode_index // chunks_size
    for video_key in video_keys:
        src = src_videos_root / f"chunk-{source_chunk:03d}" / video_key / source_name
        if not src.exists():
            raise FileNotFoundError(f"Missing video file: {src}")
        dst = dst_videos_root / f"chunk-{target_chunk:03d}" / video_key / target_name
        maybe_copy_file(src, dst, dry_run=dry_run)


def build_episodes_jsonl(source_rows, mapping):
    out = []
    for row in source_rows:
        source_episode_index = int(row["episode_index"])
        if source_episode_index not in mapping:
            continue
        updated = dict(row)
        updated["episode_index"] = mapping[source_episode_index]
        out.append(updated)
    out.sort(key=lambda row: row["episode_index"])
    return out


def build_episodes_stats_jsonl(source_rows, mapping):
    out = []
    global_index_start = 0
    for row in source_rows:
        source_episode_index = int(row["episode_index"])
        if source_episode_index not in mapping:
            continue
        updated = json.loads(json.dumps(row))
        frame_count = int(updated["stats"]["frame_index"]["count"][0])
        updated["episode_index"] = mapping[source_episode_index]
        updated["stats"]["episode_index"] = summarize_numeric_vector(
            np.full(
                int(updated["stats"]["episode_index"]["count"][0]),
                mapping[source_episode_index],
                dtype=np.float64,
            )
        )
        updated["stats"]["frame_index"] = summarize_numeric_vector(
            np.arange(frame_count, dtype=np.float64)
        )
        updated["stats"]["index"] = summarize_numeric_vector(
            np.arange(global_index_start, global_index_start + frame_count, dtype=np.float64)
        )
        global_index_start += frame_count
        out.append(updated)
    out.sort(key=lambda row: row["episode_index"])
    return out


def build_info_json(source_info, total_episodes, total_frames, total_videos):
    info = json.loads(json.dumps(source_info))
    chunks_size = int(info.get("chunks_size", 1000))
    info["total_episodes"] = total_episodes
    info["total_frames"] = total_frames
    info["total_videos"] = total_videos
    info["total_chunks"] = (total_episodes + chunks_size - 1) // chunks_size if total_episodes > 0 else 0
    info["splits"] = {"train": f"0:{total_episodes}"}
    return info


def ensure_contiguous(values, label):
    expected = list(range(len(values)))
    if list(values) != expected:
        raise ValueError(f"{label} is not contiguous 0..{len(values) - 1}")


def count_output_videos(task_root: Path):
    return len(list((task_root / "videos").glob("chunk-*/*/episode_*.mp4")))


def count_output_parquets(task_root: Path):
    return len(list((task_root / "data").glob("chunk-*/episode_*.parquet")))


def validate_task_output(output_root: Path, task_name: str, expected_static_count: int):
    task_root = target_task_root(output_root, task_name)
    meta_root = task_root / "meta"
    required = [
        meta_root / "episodes.jsonl",
        meta_root / "episodes_stats.jsonl",
        meta_root / "info.json",
        meta_root / "episode_mapping.csv",
        meta_root / "tasks.jsonl",
        meta_root / "stats.json",
        meta_root / "modality.json",
        meta_root / "embodiment.json",
    ]
    missing = [str(path) for path in required if not path.exists()]
    if missing:
        raise FileNotFoundError(f"{task_name} missing output files: {missing}")

    episodes = read_jsonl(meta_root / "episodes.jsonl")
    episode_stats = read_jsonl(meta_root / "episodes_stats.jsonl")
    info = read_json(meta_root / "info.json")
    with (meta_root / "episode_mapping.csv").open("r", encoding="utf-8", newline="") as f:
        mapping_rows = list(csv.DictReader(f))

    episode_indices = [int(row["episode_index"]) for row in episodes]
    episode_stats_indices = [int(row["episode_index"]) for row in episode_stats]
    mapping_targets = [int(row["target_episode_index"]) for row in mapping_rows]

    ensure_contiguous(episode_indices, f"{task_name} episodes.jsonl episode_index")
    ensure_contiguous(
        episode_stats_indices, f"{task_name} episodes_stats.jsonl episode_index"
    )
    ensure_contiguous(mapping_targets, f"{task_name} episode_mapping.csv target_episode_index")

    if len(episodes) != expected_static_count:
        raise ValueError(
            f"{task_name} episodes.jsonl count mismatch: {len(episodes)} != {expected_static_count}"
        )
    if len(episode_stats) != expected_static_count:
        raise ValueError(
            f"{task_name} episodes_stats.jsonl count mismatch: {len(episode_stats)} != {expected_static_count}"
        )
    if len(mapping_rows) != expected_static_count:
        raise ValueError(
            f"{task_name} episode_mapping.csv count mismatch: {len(mapping_rows)} != {expected_static_count}"
        )

    if info["total_episodes"] != expected_static_count:
        raise ValueError(
            f"{task_name} info total_episodes mismatch: {info['total_episodes']} != {expected_static_count}"
        )
    if info["splits"] != {"train": f"0:{expected_static_count}"}:
        raise ValueError(f"{task_name} unexpected split spec: {info['splits']}")

    parquet_count = count_output_parquets(task_root)
    if parquet_count != expected_static_count:
        raise ValueError(
            f"{task_name} parquet count mismatch: {parquet_count} != {expected_static_count}"
        )

    video_keys = collect_video_keys(info)
    video_count = count_output_videos(task_root)
    expected_videos = expected_static_count * len(video_keys)
    if video_count != expected_videos:
        raise ValueError(
            f"{task_name} video count mismatch: {video_count} != {expected_videos}"
        )
    if info["total_videos"] != expected_videos:
        raise ValueError(
            f"{task_name} info total_videos mismatch: {info['total_videos']} != {expected_videos}"
        )

    frame_sum = int(sum(int(row["length"]) for row in episodes))
    if info["total_frames"] != frame_sum:
        raise ValueError(
            f"{task_name} info total_frames mismatch: {info['total_frames']} != {frame_sum}"
        )

    for row in episode_stats:
        episode_index = int(row["episode_index"])
        stats = row["stats"]
        mean_episode = stats["episode_index"]["mean"][0]
        if abs(mean_episode - episode_index) > 1e-6:
            raise ValueError(
                f"{task_name} episode_stats mean episode_index mismatch for {episode_index}"
            )

    print(
        f"[validate] {task_name}: "
        f"{expected_static_count} episodes, {parquet_count} parquet files, {video_count} videos"
    )


def process_collection(
    source_root: Path,
    output_root: Path,
    task_name: str,
    collection_id: str,
    dataset_id: str,
    rows,
    overwrite: bool,
    dry_run: bool,
):
    src_root = source_lerobot_root(source_root, task_name, collection_id)
    validate_source_collection(src_root)

    source_info = read_json(src_root / "meta" / "info.json")
    source_episodes = read_jsonl(src_root / "meta" / "episodes.jsonl")
    source_episode_stats = read_jsonl(src_root / "meta" / "episodes_stats.jsonl")
    source_tasks = read_jsonl(src_root / "meta" / "tasks.jsonl")
    chunks_size = int(source_info.get("chunks_size", 1000))

    kept_rows = [row for row in rows if not row["is_moving"]]
    if not kept_rows:
        print(f"[skip] {dataset_id}: no static episodes")
        return None

    mapping = {
        int(row["source_episode_index"]): target_episode_index
        for target_episode_index, row in enumerate(kept_rows)
    }
    kept_source_episode_indices = sorted(mapping.keys())
    video_keys = collect_video_keys(source_info)

    dst_root = target_task_root(output_root, task_name)
    if dst_root.exists():
        if not overwrite:
            raise FileExistsError(
                f"Destination already exists: {dst_root}. Use --overwrite to replace it."
            )
        if not dry_run:
            safe_remove_tree(dst_root)

    if not dry_run:
        (dst_root / "meta").mkdir(parents=True, exist_ok=True)
        (dst_root / "data").mkdir(parents=True, exist_ok=True)
        (dst_root / "videos").mkdir(parents=True, exist_ok=True)

    maybe_copy_file(src_root / "meta" / "modality.json", dst_root / "meta" / "modality.json", dry_run)
    maybe_copy_file(
        src_root / "meta" / "embodiment.json",
        dst_root / "meta" / "embodiment.json",
        dry_run,
    )

    total_frames = 0
    parquet_dfs = []
    manifest_rows = []
    for source_episode_index in kept_source_episode_indices:
        target_episode_index = mapping[source_episode_index]
        source_chunk = source_episode_index // chunks_size
        target_chunk = target_episode_index // chunks_size
        src_parquet = (
            src_root
            / "data"
            / f"chunk-{source_chunk:03d}"
            / f"episode_{source_episode_index:06d}.parquet"
        )
        if not src_parquet.exists():
            raise FileNotFoundError(f"Missing parquet: {src_parquet}")
        dst_parquet = (
            dst_root
            / "data"
            / f"chunk-{target_chunk:03d}"
            / f"episode_{target_episode_index:06d}.parquet"
        )
        df = copy_episode_parquet(
            src_parquet,
            dst_parquet,
            target_episode_index=target_episode_index,
            global_index_start=total_frames,
            dry_run=dry_run,
        )
        total_frames += len(df)
        parquet_dfs.append(df)

        copy_episode_videos(
            src_videos_root=src_root / "videos",
            dst_videos_root=dst_root / "videos",
            video_keys=video_keys,
            source_episode_index=source_episode_index,
            target_episode_index=target_episode_index,
            chunks_size=chunks_size,
            dry_run=dry_run,
        )

        manifest_rows.append(
            {
                "task_name": task_name,
                "collection_id": collection_id,
                "dataset_id": dataset_id,
                "source_episode_index": source_episode_index,
                "target_episode_index": target_episode_index,
                "is_moving": False,
            }
        )

    total_episodes = len(kept_source_episode_indices)
    total_videos = total_episodes * len(video_keys)
    new_episodes = build_episodes_jsonl(source_episodes, mapping)
    new_episode_stats = build_episodes_stats_jsonl(source_episode_stats, mapping)
    new_info = build_info_json(source_info, total_episodes, total_frames, total_videos)

    data_df = pd.concat(parquet_dfs, ignore_index=True)
    rebuilt_stats = compute_feature_stats(data_df)
    aggregated_stats = aggregate_episode_stats(
        source_episode_stats,
        kept_source_episode_indices,
        mapping,
    )
    rebuilt_stats.update(aggregated_stats)

    maybe_write_jsonl(dst_root / "meta" / "episodes.jsonl", new_episodes, dry_run)
    maybe_write_jsonl(dst_root / "meta" / "episodes_stats.jsonl", new_episode_stats, dry_run)
    maybe_write_jsonl(dst_root / "meta" / "tasks.jsonl", source_tasks, dry_run)
    maybe_write_json(dst_root / "meta" / "info.json", new_info, dry_run)
    maybe_write_json(dst_root / "meta" / "stats.json", rebuilt_stats, dry_run)
    maybe_write_csv(
        dst_root / "meta" / "episode_mapping.csv",
        manifest_rows,
        fieldnames=[
            "task_name",
            "collection_id",
            "dataset_id",
            "source_episode_index",
            "target_episode_index",
            "is_moving",
        ],
        dry_run=dry_run,
    )

    print(
        f"[done] {dataset_id}: kept {total_episodes}/{len(rows)} episodes, "
        f"{total_frames} frames, {total_videos} videos"
    )
    return {
        "task_name": task_name,
        "collection_id": collection_id,
        "dataset_id": dataset_id,
        "source_episode_count": len(rows),
        "kept_episode_count": total_episodes,
        "dropped_episode_count": len(rows) - total_episodes,
        "total_frames": total_frames,
        "total_videos": total_videos,
                "output_dir": str(Path("atomic") / task_name),
    }


def write_global_summary(output_root: Path, rows, dry_run: bool):
    summary_path = output_root / "preparation_summary.json"
    payload = {
        "num_collections": len(rows),
        "source_episodes": int(sum(row["source_episode_count"] for row in rows)),
        "kept_episodes": int(sum(row["kept_episode_count"] for row in rows)),
        "dropped_episodes": int(sum(row["dropped_episode_count"] for row in rows)),
        "total_frames": int(sum(row["total_frames"] for row in rows)),
        "total_videos": int(sum(row["total_videos"] for row in rows)),
        "collections": rows,
    }
    maybe_write_json(summary_path, payload, dry_run=dry_run)


def main():
    args = parse_args()
    grouped = load_motion_flags(args.flags_csv, args.tasks)
    if not grouped:
        raise ValueError("No matching rows found in the motion CSV.")

    if args.validate == "only":
        for (task_name, _collection_id, _dataset_id), rows in sorted(grouped.items()):
            expected_static_count = sum(1 for row in rows if not row["is_moving"])
            validate_task_output(args.output_root, task_name, expected_static_count)
        print(f"[validate-summary] validated {len(grouped)} task outputs")
        return

    summaries = []
    for (task_name, collection_id, dataset_id), rows in sorted(grouped.items()):
        summary = process_collection(
            source_root=args.source_root,
            output_root=args.output_root,
            task_name=task_name,
            collection_id=collection_id,
            dataset_id=dataset_id,
            rows=rows,
            overwrite=args.overwrite,
            dry_run=args.dry_run,
        )
        if summary is not None:
            summaries.append(summary)
            if args.validate == "after" and not args.dry_run:
                validate_task_output(
                    args.output_root,
                    task_name,
                    expected_static_count=summary["kept_episode_count"],
                )

    if summaries:
        write_global_summary(args.output_root, summaries, dry_run=args.dry_run)
        print(
            "[summary] "
            f"{sum(row['kept_episode_count'] for row in summaries)} kept episodes across "
            f"{len(summaries)} collections"
        )
    else:
        print("[summary] no collections produced output")


if __name__ == "__main__":
    main()
